<?php

namespace AppBundle\Entity;

/**
 * AvoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvoirRepository extends \Doctrine\ORM\EntityRepository
{
}
