<?php

namespace AppBundle\Entity;

/**
 * BateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateauRepository extends \Doctrine\ORM\EntityRepository
{
}
