<?php

namespace AppBundle\Entity;

/**
 * CbTransSeq2014Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CbTransSeq2014Repository extends \Doctrine\ORM\EntityRepository
{
}
