<?php

namespace AppBundle\Entity;

/**
 * CbTransSeq2013Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CbTransSeq2013Repository extends \Doctrine\ORM\EntityRepository
{
}
