<?php

namespace AppBundle\Entity;

/**
 * CbTransSeq2016Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CbTransSeq2016Repository extends \Doctrine\ORM\EntityRepository
{
}
