<?php

namespace AppBundle\Entity;

/**
 * EtatInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
