<?php

namespace AppBundle\Entity;

/**
 * TraceOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
