<?php

namespace AppBundle\Entity;

/**
 * TransactionCbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionCbRepository extends \Doctrine\ORM\EntityRepository
{
}
