<?php

namespace AppBundle\Entity;

/**
 * TypeReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
