<?php

namespace AppBundle\Entity;

/**
 * TypeAdhesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAdhesionRepository extends \Doctrine\ORM\EntityRepository
{
}
