<?php

namespace AppBundle\Entity;

/**
 * VadsResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VadsResultRepository extends \Doctrine\ORM\EntityRepository
{
}
